### input directories ###

proteome_dir: proteome #this directory must exist and contain proteomes (.faa) and kegg annotations (.kegg.txt)
pepXML_dir: mass_spec
pre_align_fasta_dir: preAlign #this directory does not need to exist
raw_alignment_dir: rawAlign #this directory does not need to exist
species_info: index_umb_taxa_gca.tsv
ptm_types:
  Phospho: 80
  AcetylCarbamyl: 42
  MonoMethyl: 14
  DiMethyl: 28
  TriMethyl: 42

### alignment report parameters ###

#orthologs_to_align: #can also provide a minimum coverage instead of specific ids (ie, all>31) but this will generate a ton of files and may cause snakemake to crash due to filesystem delays. You have been warned
#   - K00016
#   - K01689
pathways:
  - ko00020
row_length: 100 #the length of each row in the final report
  #select_intervals:
  #  - [0,60]
  #  - [200,225]

### intermediate directories ###
ptm_dir: intermediates/ptm
pre_align_fasta_dir: intermediates/preAlign #this directory does not need to exist
raw_alignment_dir: intermediates/rawAlign #this directory does not need to exist
final_alignment_dir: align_reports #this directory does not need to exist
