proteome_dir: proteome #this directory must exist and contain proteomes (.faa) and kegg annotations (.kegg.txt)
pepXML_dir: mass_spec
pre_align_fasta_dir: preAlign #this directory does not need to exist
raw_alignment_dir: rawAlign #this directory does not need to exist
species_info: index_umb_taxa_gca.tsv
ptm_types:
  - AcetylCarbamyl
  - Phospho
  - MonoMethyl
  - DiMethyl
  - TriMethyl
orthologs_to_align: #can also provide a minimum coverage instead of specific ids (ie, all>31) but this will generate a ton of files and may cause snakemake to crash due to filesystem delays. You have been warned
   - K00016
   - K01689
