
# python command (usually python3 or python)
python: python3


### input directories ###

# these directories/filepaths must contain info as described in the README
proteome_dir: proteome #this directory must exist and contain proteomes (.faa) and kegg annotations (.kegg.txt)
pepXML_dir: mass_spec #this directory must exist and have one subdirectory for each ptm type
species_info: index_umb_taxa_gca.tsv #this must exist


### output directories ###

# these directories will be created if they do not exist
final_alignment_dir: align_reports
tree_final_alignments: align_reports


### PTM types ###

# must contain the name and mass shift for each type.
ptm_types:
  Phospho: 80
  AcetylCarbamyl: 42
  MonoMethyl: 14
  DiMethyl: 28
  TriMethyl: 42


### alignment report parameters ###

orthologs_to_align: #can also provide a minimum coverage instead of specific ids (ie, all>31) but this will generate a ton of files and may cause snakemake to crash due to filesystem delays. You have been warned
   - K00016
   - K01689
#pathways:
#  - ko00020
row_length: 100 #the length of each row in the final report
#select_intervals:
#  - [0,60]
#  - [200,225]


### intermediate directories ###

# these directories will be created if they do not exist
ptm_dir: intermediates/ptm
pre_align_fasta_dir: intermediates/preAlign
raw_alignment_dir: intermediates/rawAlign #cannot be the same dir as pre_align_fasta_dir
tree_intermediates: intermediates/tree
